services:
  locataire-db:
    image: postgres:14
    container_name: locataire-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - locataire_pgdata:/var/lib/postgresql/data

volumes:
  locataire_pgdata:
